"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import { Provider } from "react-redux";
import store from "@/app/redux/store";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        style={{
          color: "var(--foreground)",
          backgroundColor: "var(--background)",
        }}
      >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Provider store={store}>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
