export enum LsIconName {
    Up = 'up',
    Down = 'down',
    Upload = 'upload',
    Profile = 'profile',
    Search = 'search',
    Plus = 'plus',
    Processing = 'processing',
    Close = 'close',
    Edit = 'edit',
    Delete = 'delete',
    Duplicate = 'duplicate',
    Check = 'check',
    Animation = 'animation',
    Crown = 'crown',
    Undo = 'undo',
    Redo = 'redo',
    List = 'list',
    BulletedList = 'bulleted_list',
    ArrowTop = 'arrow_top',
    ArrowBottom = 'arrow_bottom',
    View = 'view',
    Hide = 'hide',
    Logout = "Logout",
    Save = "Save",
  }
  